language: objective-c
osx_image: xcode7.0
xcode_sdk:
    - iphonesimulator9.0
script:
    - xctool -project SCAvatarBrowserDemo/SCAvatarBrowserDemo.xcodeproj -scheme SCAvatarBrowserDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO